// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoneheartRealms.Data.Data;

#nullable disable

namespace StoneheartRealms.Data.Migrations
{
    [DbContext(typeof(StoneheartRealmsDbContext))]
    [Migration("20260601185720_InitialCore")]
    partial class InitialCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoneheartRealms.Data.Entities.Creatures.Dwarf", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte>("Energy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)100);

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<byte>("Hunger")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)100);

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Thirst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)100);

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Dwarves");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Age = 186,
                            Description = "This is the first dwarf",
                            Energy = (byte)100,
                            Gender = 0,
                            Hunger = (byte)100,
                            Name = "First Dwarf",
                            Thirst = (byte)100
                        },
                        new
                        {
                            Id = 2L,
                            Age = 186,
                            Description = "This is the second dwarf",
                            Energy = (byte)100,
                            Gender = 1,
                            Hunger = (byte)100,
                            Name = "Second Dwarf",
                            Thirst = (byte)100
                        },
                        new
                        {
                            Id = 3L,
                            Age = 186,
                            Description = "This is the third dwarf",
                            Energy = (byte)100,
                            Gender = 0,
                            Hunger = (byte)100,
                            Name = "Third Dwarf",
                            Thirst = (byte)100
                        },
                        new
                        {
                            Id = 4L,
                            Age = 186,
                            Description = "This is the fourth dwarf",
                            Energy = (byte)100,
                            Gender = 0,
                            Hunger = (byte)100,
                            Name = "Fourth Dwarf",
                            Thirst = (byte)100
                        },
                        new
                        {
                            Id = 5L,
                            Age = 186,
                            Description = "This is the fifth dwarf",
                            Energy = (byte)100,
                            Gender = 1,
                            Hunger = (byte)100,
                            Name = "Fifth Dwarf",
                            Thirst = (byte)100
                        });
                });

            modelBuilder.Entity("StoneheartRealms.Data.Entities.Jobs.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is a farmer",
                            Name = "Farmer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is a miner",
                            Name = "Miner"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is a cook",
                            Name = "Cook"
                        });
                });

            modelBuilder.Entity("StoneheartRealms.Data.Entities.Creatures.Dwarf", b =>
                {
                    b.HasOne("StoneheartRealms.Data.Entities.Jobs.Job", "Job")
                        .WithMany("Dwarves")
                        .HasForeignKey("JobId");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("StoneheartRealms.Data.Entities.Jobs.Job", b =>
                {
                    b.Navigation("Dwarves");
                });
#pragma warning restore 612, 618
        }
    }
}
