// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoneheartRealms.Data.Data;

#nullable disable

namespace StoneheartRealms.Data.Migrations
{
    [DbContext(typeof(StoneheartRealmsDbContext))]
    [Migration("20260624142600_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoneheartRealms.Data.Entities.Creatures.Dwarf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte>("Energy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)100);

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<byte>("Hunger")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)100);

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Thirst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)100);

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Dwarves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 186,
                            Description = "This is the first dwarf",
                            Energy = (byte)100,
                            Gender = 0,
                            Hunger = (byte)100,
                            JobId = 1,
                            Name = "First Dwarf",
                            Thirst = (byte)100
                        },
                        new
                        {
                            Id = 2,
                            Age = 186,
                            Description = "This is the second dwarf",
                            Energy = (byte)100,
                            Gender = 1,
                            Hunger = (byte)100,
                            JobId = 2,
                            Name = "Second Dwarf",
                            Thirst = (byte)100
                        },
                        new
                        {
                            Id = 3,
                            Age = 186,
                            Description = "This is the third dwarf",
                            Energy = (byte)100,
                            Gender = 0,
                            Hunger = (byte)100,
                            JobId = 3,
                            Name = "Third Dwarf",
                            Thirst = (byte)100
                        },
                        new
                        {
                            Id = 4,
                            Age = 186,
                            Description = "This is the fourth dwarf",
                            Energy = (byte)100,
                            Gender = 0,
                            Hunger = (byte)100,
                            JobId = 4,
                            Name = "Fourth Dwarf",
                            Thirst = (byte)100
                        },
                        new
                        {
                            Id = 5,
                            Age = 186,
                            Description = "This is the fifth dwarf",
                            Energy = (byte)100,
                            Gender = 1,
                            Hunger = (byte)100,
                            JobId = 5,
                            Name = "Fifth Dwarf",
                            Thirst = (byte)100
                        },
                        new
                        {
                            Id = 6,
                            Age = 186,
                            Description = "This is the sixth dwarf",
                            Energy = (byte)100,
                            Gender = 0,
                            Hunger = (byte)100,
                            JobId = 6,
                            Name = "Sixth Dwarf",
                            Thirst = (byte)100
                        },
                        new
                        {
                            Id = 7,
                            Age = 186,
                            Description = "This is the seventh dwarf",
                            Energy = (byte)100,
                            Gender = 1,
                            Hunger = (byte)100,
                            JobId = 7,
                            Name = "Seventh Dwarf",
                            Thirst = (byte)100
                        },
                        new
                        {
                            Id = 8,
                            Age = 186,
                            Description = "This is the eighth dwarf",
                            Energy = (byte)100,
                            Gender = 0,
                            Hunger = (byte)100,
                            JobId = 8,
                            Name = "Eighth Dwarf",
                            Thirst = (byte)100
                        });
                });

            modelBuilder.Entity("StoneheartRealms.Data.Entities.Jobs.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is a farmer",
                            Name = "Farmer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is a fisher",
                            Name = "Fisher"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is a hunter",
                            Name = "Hunter"
                        },
                        new
                        {
                            Id = 4,
                            Description = "This is a cook",
                            Name = "Cook"
                        },
                        new
                        {
                            Id = 5,
                            Description = "This is a miner",
                            Name = "Miner"
                        },
                        new
                        {
                            Id = 6,
                            Description = "This is a blacksmith",
                            Name = "Blacksmith"
                        },
                        new
                        {
                            Id = 7,
                            Description = "This is a woodcutter",
                            Name = "Woodcutter"
                        },
                        new
                        {
                            Id = 8,
                            Description = "This is a administrator of the colony",
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("StoneheartRealms.Data.Entities.Storage.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StorageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("StorageId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500,
                            ResourceTypeId = 1,
                            StorageId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 150,
                            ResourceTypeId = 2,
                            StorageId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 200,
                            ResourceTypeId = 3,
                            StorageId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 300,
                            ResourceTypeId = 4,
                            StorageId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 50,
                            ResourceTypeId = 5,
                            StorageId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 50,
                            ResourceTypeId = 6,
                            StorageId = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 100,
                            ResourceTypeId = 7,
                            StorageId = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 200,
                            ResourceTypeId = 8,
                            StorageId = 1
                        });
                });

            modelBuilder.Entity("StoneheartRealms.Data.Entities.Storage.ResourceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResourceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Iron"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Stone"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wood"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Meat"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Wheat"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Food"
                        });
                });

            modelBuilder.Entity("StoneheartRealms.Data.Entities.Storage.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Storages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Main Storage"
                        });
                });

            modelBuilder.Entity("StoneheartRealms.Data.Entities.Creatures.Dwarf", b =>
                {
                    b.HasOne("StoneheartRealms.Data.Entities.Jobs.Job", "Job")
                        .WithMany("Dwarves")
                        .HasForeignKey("JobId");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("StoneheartRealms.Data.Entities.Storage.Resource", b =>
                {
                    b.HasOne("StoneheartRealms.Data.Entities.Storage.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoneheartRealms.Data.Entities.Storage.Storage", "Storage")
                        .WithMany("Resources")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceType");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("StoneheartRealms.Data.Entities.Jobs.Job", b =>
                {
                    b.Navigation("Dwarves");
                });

            modelBuilder.Entity("StoneheartRealms.Data.Entities.Storage.Storage", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
